### ISSUE TITLE
Figure out how to obtain deployment name + namespace

### ISSUE THREAD

**Issue by vlerkin** [q-m/scrapyd-k8s#22]
Figure out how to obtain scrapyd-k8s' deployment name + current namespace from within scrapyd-k8s.
This will probably [need the Downward API](https://stackoverflow.com/questions/42274229/kubernetes-deployment-name-from-within-a-pod).

Document this in  https://github.com/q-m/scrapyd-k8s/issues/13.

**Comment by vlerkin** [comment]
During the first look it seems not complicated to achieve, docs provide a clear way, for example, how to implement it using[ environment variables](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/), also possible using volumes. Working on this issue.

**Comment by wvengen** [comment]
Also, the namespace can be used as a default namespace. Note that the pod's (=deployment's) namespace can be found in `/var/run/secrets/kubernetes.io/serviceaccount/namespace` already.
Also see https://stackoverflow.com/a/57809472

**Comment by vlerkin** [comment]
Yes, sorry, for deployment name we need to check `metadata.labels`.
to be clear is this the namespace (pod namespace) we want to get?

```
- name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

Ok, thank you.

**Comment by wvengen** [comment]
Yes, pod namespace is fine.

**Comment by wvengen** [comment]
While at it, there are two cases: in-cluster (what you looked at here) and when running not on the cluster itself.

When not running on the cluster, the kubernetes Python client reads the configuration (like, from `~/.kube`), it should be possible to get the default namespace too, so that can be used.

**Comment by vlerkin** [comment]
> when running not on the cluster itself

Could you please give more details about this? Where k8s runs if not on the cluster? Do you use a different yaml file for that or the same?

**Comment by wvengen** [comment]
Please see the different ways to run scrapyd-k8s in the README. You can run it in Docker, in Kubernetes, and Local. "when running not on the cluster itself" would be for the last (Local).

**Comment by vlerkin** [comment]
Changes in `kubernetes.yaml` file:

```
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
```

Extraction of deployment name is done following the example from the last comment of [this stack overflow issue](https://stackoverflow.com/questions/42274229/kubernetes-deployment-name-from-within-a-pod) you recommended to look into, pod namespace extracted following [Kubernetes docs](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/).

Result:

```
valeriiaklestova@BA92-HC7TN99KW6 scrapyd-k8s % kubectl exec -it scrapyd-k8s-745dc46d6f-894cn sh                       
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
$ echo $DEPLOYMENT_NAME
scrapyd-k8s
$ echo $MY_POD_NAMESPACE
default
```

Is this something you had in mind?
